### ISSUE TITLE
Request for check on CIDR of unusual size

### ISSUE THREAD

**Issue by JesseBowling** [collectiveintel/cif-v1#83]
Recently an entry in a malc0de.com feed included an entry with a /1 CIDR address in it. This managed to bypass all whitelist functionality and was output in a feed. Hijinks ensued.

Would like to request a configurable item as a final check in feed generation that would allow for the rejection of feed items with a CIDR notation larger (smaller) than X.

**Comment by wesyoung** [comment]
lol, nice.

i think it's gonna go somewhere around here:

https://github.com/collectiveintel/cif-v1/blob/master/cif-smrt/lib/CIF/Smrt/Plugin/Preprocessor/Address.pm

need to test it out though...

**Comment by wesyoung** [comment]
i'm thinking longer term, you'll have to enable a feature (per feed) that says "yes, < /32 is allowed and/or everything down to a /X" so by default, "normal" feeds can't push anything < /32...

**Comment by wesyoung** [comment]
give this one a shot.. (testing in production atm..)

https://github.com/collectiveintel/cif-v1/releases/tag/v1.0.4-alpha.3

you can control it with "max_prefix" in a config.. defaults to /14

also had to implement some "this smells like a url..." type fixes too.

lmk

**Comment by wesyoung** [comment]
fixed in:

https://github.com/collectiveintel/cif-v1/releases/tag/v1.0.4-FINAL
