### ISSUE TITLE
Exception failed installation

### ISSUE THREAD

**Issue by xsallowed** [collectiveintel/cif-v1#87]
Hello 
I am seeing following error. Can anyone help how should i resolve this error.

Regards

t/lives_and.t ... 
Failed 1/3 subtests 
t/preserve.t .... ok
t/return.t ...... ok
t/rt.t .......... ok
t/stacktrace.t .. ok
t/throws_ok.t ... ok
## Test Summary Report

t/Exception.t (Wstat: 0 Tests: 20 Failed: 0)
  TODO passed:   20
t/lives_and.t (Wstat: 0 Tests: 3 Failed: 1)
  Failed test:  3
Files=11, Tests=53,  1 wallclock secs ( 0.06 usr  0.01 sys +  0.50 cusr  0.05 csys =  0.62 CPU)
Result: FAIL
Failed 1/11 test programs. 1/53 subtests failed.
-> FAIL Installing Test::Exception failed. See /home/cif/.cpanm/work/1463062088.20257/build.log for details. Retry with --force to force install it.

**Comment by giovino** [comment]
We saw this in CIFv2 as well. https://github.com/csirtgadgets/massive-octo-spice/issues/415

It looks like Test::Simple was recently updated and that is causing a test to fail in Test::Exception. You have a couple of choices:
1. Force the install of Test::Exception
2. Install the previous version of Test::Simple.. that was the method we chose in CIFv2. https://github.com/csirtgadgets/massive-octo-spice/commit/e2f493d519ff48886add75003bd034d2e53e561b

In theory either should work although I did not test the it on CIFv1.
